### ISSUE TITLE
Building Mantle 1.0.2 in Moqui 1.5.3

### ISSUE THREAD

**Issue by klempie** [moqui/mantle#37]
I am currently trying to build Moqui 1.5.3 while adding Mantle 1.0.2.

I can run build, load and run tasks for Moqui successfully if I do not include the Mantle component. When I include the Mantle component, I get the below build error. This is followed by a bunch of other SQL errors due to the PARTY_ID column not being available.

--- 85061    [main] ERROR g.moqui.impl.service.ServiceCallSyncImpl 
 Error running service [store#moqui.security.UserAccount]
org.moqui.entity.EntityException: Error in refresh of [[moqui.security.UserAccount: [userId:_NA_, username:_NA_, userFullName:Not Applicable, currentPassword:null, disabled:Y]]]
	at org.moqui.impl.entity.EntityValueImpl.refreshExtended(EntityValueImpl.groovy:248)
	at org.moqui.impl.entity.EntityValueBase.refresh(EntityValueBase.groovy:1277)
	at org.moqui.impl.entity.EntityValueBase.createOrUpdate(EntityValueBase.groovy:452)
	at org.moqui.impl.entity.EntityValueBase.store(EntityValueBase.groovy:459)
	at org.moqui.impl.service.runner.EntityAutoServiceRunner.storeRecursive(EntityAutoServiceRunner.groovy:378)
	at org.moqui.impl.service.runner.EntityAutoServiceRunner.storeEntity(EntityAutoServiceRunner.groovy:333)
	at org.moqui.impl.service.ServiceCallSyncImpl.runImplicitEntityAuto(ServiceCallSyncImpl.groovy:405)
	at org.moqui.impl.service.ServiceCallSyncImpl.callSingle(ServiceCallSyncImpl.groovy:203)
	at org.moqui.impl.service.ServiceCallSyncImpl.call(ServiceCallSyncImpl.groovy:135)
	at org.moqui.impl.entity.EntityDataLoaderImpl$LoadValueHandler.handlePlainMap(EntityDataLoaderImpl.groovy:352)
	at org.moqui.impl.entity.EntityDataLoaderImpl$EntityXmlHandler.endElement(EntityDataLoaderImpl.groovy:605)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:183)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1343)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at org.moqui.impl.entity.EntityDataLoaderImpl.loadSingleFile(EntityDataLoaderImpl.groovy:279)
	at org.moqui.impl.entity.EntityDataLoaderImpl.internalRun(EntityDataLoaderImpl.groovy:249)
	at org.moqui.impl.entity.EntityDataLoaderImpl.load(EntityDataLoaderImpl.groovy:125)
	at org.moqui.Moqui.loadData(Moqui.java:97)
	at MoquiStart.main(MoquiStart.java:104)
Caused by: org.moqui.entity.EntityException: Error in query for:SELECT USERNAME, USER_FULL_NAME, CURRENT_PASSWORD, PASSWORD_SALT, PASSWORD_HASH_TYPE, PASSWORD_SET_DATE, PASSWORD_HINT, HAS_LOGGED_OUT, DISABLED, DISABLED_DATE_TIME, SUCCESSIVE_FAILED_LOGINS, REQUIRE_PASSWORD_CHANGE, CURRENCY_UOM_ID, LOCALE, TIME_ZONE, EXTERNAL_USER_ID, EMAIL_ADDRESS, PARTY_ID, LAST_UPDATED_STAMP FROM public.USER_ACCOUNT WHERE USER_ID=?
	at org.moqui.impl.entity.EntityQueryBuilder.executeQuery(EntityQueryBuilder.groovy:104)
	at org.moqui.impl.entity.EntityValueImpl.refreshExtended(EntityValueImpl.groovy:235)
	... 26 more
Caused by: org.postgresql.util.PSQLException: ERROR: column "party_id" does not exist
  Position: 287
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:304)
	at org.postgresql.ds.jdbc23.AbstractJdbc23PooledConnection$StatementHandler.invoke(AbstractJdbc23PooledConnection.java:453)
	at com.sun.proxy.$Proxy7.executeQuery(Unknown Source)
	at bitronix.tm.resource.jdbc.proxy.PreparedStatementJavaProxy.executeQuery(PreparedStatementJavaProxy.java:102)
	at bitronix.tm.resource.jdbc.proxy.JavaProxyBase.invoke(JavaProxyBase.java:54)
	at com.sun.proxy.$Proxy27.executeQuery(Unknown Source)
java.lang.IllegalArgumentException: Error loading entity data file [jar:file:execwartmp/moqui_temp3064154677502764072WEB-INF_lib_moqui-framework-1.5.3.jar.!/entity/SecurityEntities.xml]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:71)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:81)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:232)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:252)
	at org.moqui.impl.entity.EntityDataLoaderImpl.loadSingleFile(EntityDataLoaderImpl.groovy:299)
	at org.moqui.impl.entity.EntityDataLoaderImpl$loadSingleFile$1.callCurrent(Unknown Source)
	at org.moqui.impl.entity.EntityDataLoaderImpl.internalRun(EntityDataLoaderImpl.groovy:249)
	at org.moqui.impl.entity.EntityDataLoaderImpl$internalRun$0.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:151)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:179)
	at org.moqui.impl.entity.EntityDataLoaderImpl.load(EntityDataLoaderImpl.groovy:125)
	at org.moqui.Moqui.loadData(Moqui.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at MoquiStart.main(MoquiStart.java:104)
Caused by: org.moqui.BaseException: Error handling data load plain Map: Error in refresh of [[moqui.security.UserAccount: [userId:_NA_, username:_NA_, userFullName:Not Applicable, currentPassword:null, disabled:Y]]]
Error in query for:SELECT USERNAME, USER_FULL_NAME, CURRENT_PASSWORD, PASSWORD_SALT, PASSWORD_HASH_TYPE, PASSWORD_SET_DATE, PASSWORD_HINT, HAS_LOGGED_OUT, DISABLED, DISABLED_DATE_TIME, SUCCESSIVE_FAILED_LOGINS, REQUIRE_PASSWORD_CHANGE, CURRENCY_UOM_ID, LOCALE, TIME_ZONE, EXTERNAL_USER_ID, EMAIL_ADDRESS, PARTY_ID, LAST_UPDATED_STAMP FROM public.USER_ACCOUNT WHERE USER_ID=?
ERROR: column "party_id" does not exist
  Position: 287

	at org.moqui.impl.entity.EntityDataLoaderImpl$LoadValueHandler.handlePlainMap(EntityDataLoaderImpl.groovy:357)
	at org.moqui.impl.entity.EntityDataLoaderImpl$EntityXmlHandler.endElement(EntityDataLoaderImpl.groovy:605)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:183)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1343)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at org.moqui.impl.entity.EntityQueryBuilder.executeQuery(EntityQueryBuilder.groovy:100)
	... 27 more

**Comment by jonesde** [comment]
This is not a Mantle issue, but rather an issue with Moqui Framework and Postgres. There is a discussion about this in the LinkedIn forum:

https://www.linkedin.com/grp/post/4640689-5989914070462062594

The problem is that with Postgres the DB meta data updating is not working, in this case it failed to automatically add the missing column on USER_ACCOUNT after Mantle was put in place, which adds a PARTY_ID column.

This will work if you clean out your DB (delete all tables, or drop and recreate the DB) and then run Moqui from the beginning with Mantle in place.

**Comment by klempie** [comment]
Thanks David. The suggested fix worked! At last I can start digging into Mantle!

**Comment by jonesde** [comment]
On a side note, the easiest way to play with Moqui, Mantle, etc is to use the default configuration with the H2 database.
