### ISSUE TITLE
Failing test on local machine?

### ISSUE THREAD

**Issue by samhamilton** [moqui/mantle#75]
Hi David, 

I am getting a failing test when working with a fresh copy of Moqui and Mantle e.g. no changes at all. 

I have looked at the Travis builds and can't see it failing there and the only difference I have is that Travis is running Java 7 and my local machine is running Java 8?

Thanks
Sam

```
Running test: Test depreciate Fixed Assets(OrderProcureToPayBasicFlow)

OrderProcureToPayBasicFlow > depreciate Fixed Assets STANDARD_OUT
    --- 35466    [    Test worker] INFO   org.moqui.impl.context.LoggerFacadeImpl
     Calculating and posting depreciation for organizations: [ORG_ZIZI_RETAIL], assets: [55402, 55403]
    --- 35724    [    Test worker] WARN  moqui.impl.context.TransactionFacadeImpl
     Transaction set rollback only. The rollback was originally caused by: Error running service [mantle.party.TimeServices.create#TimePeriod] (message): Existing Fiscal Month Time Period found for Party [ORG_ZIZI_RETAIL] starting on 2015-10-01

    --- 35727    [    Test worker] WARN  moqui.impl.context.TransactionFacadeImpl
     Transaction set rollback only for [Error running service [mantle.party.TimeServices.create#TimePeriod] (message): Existing Fiscal Month Time Period found for Party [ORG_ZIZI_RETAIL] starting on 2015-10-01
    ]. Here is the current location:
    org.moqui.BaseException: Set rollback only location
    	at org.moqui.impl.context.TransactionFacadeImpl.setRollbackOnly(TransactionFacadeImpl.groovy:457)
    	at org.moqui.impl.context.TransactionFacadeImpl.rollback(TransactionFacadeImpl.groovy:414)
    	at org.moqui.impl.service.ServiceCallSyncImpl.callSingle(ServiceCallSyncImpl.groovy:271)
    	at org.moqui.impl.service.ServiceCallSyncImpl.call(ServiceCallSyncImpl.groovy:137)
    	at mantle_ledger_LedgerServices_get_OrganizationFiscalTimePeriods.run(mantle_ledger_LedgerServices_get_OrganizationFiscalTimePeriods:40)
    	at org.moqui.impl.actions.XmlAction.run(XmlAction.groovy:99)
    	at org.moqui.impl.service.runner.InlineServiceRunner.runService(InlineServiceRunner.groovy:53)
    	at org.moqui.impl.service.ServiceCallSyncImpl.callSingle(ServiceCallSyncImpl.groovy:260)
    	at org.moqui.impl.service.ServiceCallSyncImpl.call(ServiceCallSyncImpl.groovy:137)
    	at mantle_ledger_LedgerServices_post_AcctgTrans.run(mantle_ledger_LedgerServices_post_AcctgTrans:102)
    	at org.moqui.impl.actions.XmlAction.run(XmlAction.groovy:99)
    	at org.moqui.impl.service.runner.InlineServiceRunner.runService(InlineServiceRunner.groovy:53)
    	at org.moqui.impl.service.ServiceCallSyncImpl.callSingle(ServiceCallSyncImpl.groovy:260)
    	at org.moqui.impl.service.ServiceCallSyncImpl.call(ServiceCallSyncImpl.groovy:137)
    	at mantle_ledger_AssetAutoPostServices_post_FixedAssetDepreciation.run(mantle_ledger_AssetAutoPostServices_post_FixedAssetDepreciation:180)
    	at org.moqui.impl.actions.XmlAction.run(XmlAction.groovy:99)
    	at org.moqui.impl.service.runner.InlineServiceRunner.runService(InlineServiceRunner.groovy:53)
    	at org.moqui.impl.service.ServiceCallSyncImpl.callSingle(ServiceCallSyncImpl.groovy:260)
    	at org.moqui.impl.service.ServiceCallSyncImpl.call(ServiceCallSyncImpl.groovy:137)
    	at mantle_ledger_AssetAutoPostServices_calculateAndPost_FixedAssetDepreciation.run(mantle_ledger_AssetAutoPostServices_calculateAndPost_FixedAssetDepreciation:42)
    	at org.moqui.impl.actions.XmlAction.run(XmlAction.groovy:99)
    	at org.moqui.impl.service.runner.InlineServiceRunner.runService(InlineServiceRunner.groovy:53)
    	at org.moqui.impl.service.ServiceCallSyncImpl.callSingle(ServiceCallSyncImpl.groovy:260)
    	at org.moqui.impl.service.ServiceCallSyncImpl.call(ServiceCallSyncImpl.groovy:137)
    	at mantle_ledger_AssetAutoPostServices_calculateAndPost_AllFixedAssetDepreciations.run(mantle_ledger_AssetAutoPostServices_calculateAndPost_AllFixedAssetDepreciations:49)
    	at org.moqui.impl.actions.XmlAction.run(XmlAction.groovy:99)
    	at org.moqui.impl.service.runner.InlineServiceRunner.runService(InlineServiceRunner.groovy:53)
    	at org.moqui.impl.service.ServiceCallSyncImpl.callSingle(ServiceCallSyncImpl.groovy:260)
    	at org.moqui.impl.service.ServiceCallSyncImpl.call(ServiceCallSyncImpl.groovy:137)
    	at OrderProcureToPayBasicFlow.$spock_feature_0_13(OrderProcureToPayBasicFlow.groovy:704)
    	at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:153)
    	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:84)
    	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:480)
    	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:463)
    	at org.spockframework.runtime.BaseSpecRunner.runFeatureMethod(BaseSpecRunner.java:405)
    	at org.spockframework.runtime.BaseSpecRunner.doRunIteration(BaseSpecRunner.java:324)
    	at org.spockframework.runtime.BaseSpecRunner$6.invoke(BaseSpecRunner.java:309)
    	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:480)
    	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:463)
    	at org.spockframework.runtime.BaseSpecRunner.runIteration(BaseSpecRunner.java:288)
    	at org.spockframework.runtime.BaseSpecRunner.initializeAndRunIteration(BaseSpecRunner.java:278)
    	at org.spockframework.runtime.BaseSpecRunner.runSimpleFeature(BaseSpecRunner.java:269)
    	at org.spockframework.runtime.BaseSpecRunner.doRunFeature(BaseSpecRunner.java:263)
    	at org.spockframework.runtime.BaseSpecRunner$5.invoke(BaseSpecRunner.java:246)
    	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:480)
    	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:463)
    	at org.spockframework.runtime.BaseSpecRunner.runFeature(BaseSpecRunner.java:238)
    	at org.spockframework.runtime.BaseSpecRunner.runFeatures(BaseSpecRunner.java:188)
    	at org.spockframework.runtime.BaseSpecRunner.doRunSpec(BaseSpecRunner.java:98)
    	at org.spockframework.runtime.BaseSpecRunner$1.invoke(BaseSpecRunner.java:84)
    	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:480)
    	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:463)
    	at org.spockframework.runtime.BaseSpecRunner.runSpec(BaseSpecRunner.java:76)
    	at org.spockframework.runtime.BaseSpecRunner.run(BaseSpecRunner.java:67)
    	at org.spockframework.runtime.Sputnik.run(Sputnik.java:63)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:105)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
    	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    --- 35761    [    Test worker] WARN  moqui.impl.context.TransactionFacadeImpl
     Transaction rollback. The rollback was originally caused by: Error running service [mantle.ledger.AssetAutoPostServices.calculateAndPost#AllFixedAssetDepreciations] (message): Existing Fiscal Month Time Period found for Party [ORG_ZIZI_RETAIL] starting on 2015-10-01

    --- 35773    [    Test worker] WARN  moqui.impl.context.TransactionFacadeImpl
     Transaction rollback for [Error running service [mantle.ledger.AssetAutoPostServices.calculateAndPost#AllFixedAssetDepreciations] (message): Existing Fiscal Month Time Period found for Party [ORG_ZIZI_RETAIL] starting on 2015-10-01
    ]. Here is the current location:
    org.moqui.BaseException: Rollback location
    	at org.moqui.impl.context.TransactionFacadeImpl.rollback(TransactionFacadeImpl.groovy:429)
    	at org.moqui.impl.context.TransactionFacadeImpl.rollback(TransactionFacadeImpl.groovy:412)
    	at org.moqui.impl.service.ServiceCallSyncImpl.callSingle(ServiceCallSyncImpl.groovy:271)
    	at org.moqui.impl.service.ServiceCallSyncImpl.call(ServiceCallSyncImpl.groovy:137)
    	at OrderProcureToPayBasicFlow.$spock_feature_0_13(OrderProcureToPayBasicFlow.groovy:704)
    	at org.spockframework.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:153)
    	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:84)
    	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:480)
    	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:463)
    	at org.spockframework.runtime.BaseSpecRunner.runFeatureMethod(BaseSpecRunner.java:405)
    	at org.spockframework.runtime.BaseSpecRunner.doRunIteration(BaseSpecRunner.java:324)
    	at org.spockframework.runtime.BaseSpecRunner$6.invoke(BaseSpecRunner.java:309)
    	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:480)
    	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:463)
    	at org.spockframework.runtime.BaseSpecRunner.runIteration(BaseSpecRunner.java:288)
    	at org.spockframework.runtime.BaseSpecRunner.initializeAndRunIteration(BaseSpecRunner.java:278)
    	at org.spockframework.runtime.BaseSpecRunner.runSimpleFeature(BaseSpecRunner.java:269)
    	at org.spockframework.runtime.BaseSpecRunner.doRunFeature(BaseSpecRunner.java:263)
    	at org.spockframework.runtime.BaseSpecRunner$5.invoke(BaseSpecRunner.java:246)
    	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:480)
    	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:463)
    	at org.spockframework.runtime.BaseSpecRunner.runFeature(BaseSpecRunner.java:238)
    	at org.spockframework.runtime.BaseSpecRunner.runFeatures(BaseSpecRunner.java:188)
    	at org.spockframework.runtime.BaseSpecRunner.doRunSpec(BaseSpecRunner.java:98)
    	at org.spockframework.runtime.BaseSpecRunner$1.invoke(BaseSpecRunner.java:84)
    	at org.spockframework.runtime.BaseSpecRunner.invokeRaw(BaseSpecRunner.java:480)
    	at org.spockframework.runtime.BaseSpecRunner.invoke(BaseSpecRunner.java:463)
    	at org.spockframework.runtime.BaseSpecRunner.runSpec(BaseSpecRunner.java:76)
    	at org.spockframework.runtime.BaseSpecRunner.run(BaseSpecRunner.java:67)
    	at org.spockframework.runtime.Sputnik.run(Sputnik.java:63)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:105)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
    	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    --- 35934    [    Test worker] INFO                OrderProcureToPayBasicFlow
     Checked 44 fields
    --- 35935    [    Test worker] INFO                OrderProcureToPayBasicFlow
     Field [mantle.product.asset.Asset.depreciation] did not match; check (file) value [283.33], db value [null] for primary key [[assetId:55402]]
    --- 35938    [    Test worker] INFO                OrderProcureToPayBasicFlow
     Entity [mantle.product.asset.AssetDepreciation] record not found for primary key [[timePeriodId:55100, assetId:55402]]
    --- 35938    [    Test worker] INFO                OrderProcureToPayBasicFlow
     Entity [mantle.ledger.transaction.AcctgTrans] record not found for primary key [[acctgTransId:55407]]
    --- 35939    [    Test worker] INFO                OrderProcureToPayBasicFlow
     Entity [mantle.ledger.transaction.AcctgTransEntry] record not found for primary key [[acctgTransEntrySeqId:01, acctgTransId:55407]]
    --- 35940    [    Test worker] INFO                OrderProcureToPayBasicFlow
     Entity [mantle.ledger.transaction.AcctgTransEntry] record not found for primary key [[acctgTransEntrySeqId:02, acctgTransId:55407]]
    --- 35941    [    Test worker] INFO                OrderProcureToPayBasicFlow
     Entity [mantle.product.asset.AssetDepreciation] record not found for primary key [[timePeriodId:55100, assetId:55403]]
    --- 35942    [    Test worker] INFO                OrderProcureToPayBasicFlow
     Entity [mantle.ledger.transaction.AcctgTrans] record not found for primary key [[acctgTransId:55408]]
    --- 35943    [    Test worker] INFO                OrderProcureToPayBasicFlow
     Entity [mantle.ledger.transaction.AcctgTransEntry] record not found for primary key [[acctgTransEntrySeqId:01, acctgTransId:55408]]
    --- 35944    [    Test worker] INFO                OrderProcureToPayBasicFlow
     Entity [mantle.ledger.transaction.AcctgTransEntry] record not found for primary key [[acctgTransEntrySeqId:02, acctgTransId:55408]]
    --- 35945    [    Test worker] INFO                OrderProcureToPayBasicFlow
     Entity [mantle.ledger.account.GlAccountOrgTimePeriod] record not found for primary key [[glAccountId:182000000, timePeriodId:55100, organizationPartyId:ORG_ZIZI_RETAIL]]
    --- 35945    [    Test worker] INFO                OrderProcureToPayBasicFlow
     Entity [mantle.ledger.account.GlAccountOrgTimePeriod] record not found for primary key [[glAccountId:672000000, timePeriodId:55100, organizationPartyId:ORG_ZIZI_RETAIL]]
    --- 35951    [    Test worker] WARN                OrderProcureToPayBasicFlow
     Existing Fiscal Month Time Period found for Party [ORG_ZIZI_RETAIL] starting on 2015-10-01


OrderProcureToPayBasicFlow > depreciate Fixed Assets FAILED
    java.lang.NoClassDefFoundError
```

**Comment by jonesde** [comment]
I'm running Java 8 on my local machine (on OS X) and with the latest code the tests all completed successfully (Moqui and Mantle).

This may be an issue running tests on a database after they've already been run (i.e. instead of a fresh database with gradle cleanAll load)... just a guess.

**Comment by samhamilton** [comment]
It was with a clean database, will do some more testing this week, very strange.

**Comment by samhamilton** [comment]
Ok I have some weirdness going on with local, sorry about that David.

**Comment by jonesde** [comment]
I'm seeing this same sort of message on the Travis CI services (i.e. "Existing Fiscal Month Time Period found for Party [ORG_ZIZI_RETAIL] starting on 2015-10-01"). I'm still not sure what is causing it as I can't reproduce it locally. 

There seems to be something funny with the TimePeriod queries or data/time calculations on certain days, like last day of the month (this just started happening on Travis CI today), and only on certain systems... perhaps only on Linux?

I made some changes trying to fix it, like using the getOrCreate#TimePeriod service instead of create#TimePeriod. That works, but the numbers in the data validation in the Spock tests don't come out the same... I'm guessing because it ends up splitting transactions over multiple periods that should be the same since the posted totals are lower than expected. I'm not sure about this because I can't reproduce it locally and see what other data looks like after the tests. Still, that's just a symptom and is only a hint at the real cause of the issue.

Anyway, in some form this issue persists...
